name: Cleanup Old Workflow Runs

on:
  schedule:
    - cron: '0 0 * * *'  # Запускать каждый день в полночь

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y curl
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install -y gh

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.ERASE_TOKEN }}"

      - name: Delete old workflow runs
        run: |
          REPO_OWNER="${{ github.repository_owner }}"
          REPO_NAME="${{ github.event.repository.name }}"
          DAYS_OLD=3  # Удалить workflow runs старше 3 дней

          # Получаем список workflow runs старше указанного количества дней
          OLD_RUNS=$(gh api repos/$REPO_OWNER/$REPO_NAME/actions/runs --jq ".workflow_runs[] | select(.created_at < \"$(date -u -d "$DAYS_OLD days ago" +%Y-%m-%dT%H:%M:%SZ)\") | .id")

          # Удаляем каждый старый workflow run
          for RUN_ID in $OLD_RUNS; do
              echo "Deleting workflow run $RUN_ID..."
              gh api repos/$REPO_OWNER/$REPO_NAME/actions/runs/$RUN_ID -X DELETE
          done

          echo "Old workflow runs deleted successfully."
