version: '3.8'

services:
  web:
    build: .
    container_name: django_app
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    ports:
      - "80:80"  # Nginx слушает порт 80
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SECRET_KEY=django-insecure-wf=md00ywe6f2a_l(&re&c9lvdbuoys(63gsp8m2=-x#e^(i9u
      - DJANGO_DEBUG=False            
