openapi: 3.0.0
info:
  title: Park API
  version: 1.0.0
paths:
  /api/login:
    post:
      summary: Авторизация пользователя
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Успешная авторизация

  /api/users/{id}:
    put:
      summary: Обновление пользователя
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        '200':
          description: Пользователь обновлен
