---
stages:
  - sast
  - dast

variables:
  ZAP_TARGET: http://89.169.164.174:80
  ZAP_OPTIONS: -a

sast:
  stage: sast
  image: python:3.12
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - pip install semgrep
    - semgrep --config=p/ci --json > semgrep-sast-report.json
  artifacts:
    paths:
      - semgrep-sast-report.json
    expire_in: 1 week

dast:
  stage: dast
  image: owasp/zap2docker-live
  script:
    - echo "Starting DAST scan..."
    - zap-baseline.py -t $ZAP_TARGET $ZAP_OPTIONS -r zap-report.html -w zap-report.md || echo "DAST scan failed"
  artifacts:
    paths:
      - zap-report.html
      - zap-report.md
    expire_in: 1 week
