name: Bandit SAST Scan
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  bandit-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install Bandit
        run: pip install bandit
      - name: Run Bandit SAST
        run: |
          bandit -r . -f json -o bandit-report.json
      - name: Upload JSON Report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-json-report
          path: bandit-report.json
      - name: Convert JSON to HTML (Optional)
        run: >
          pip install jinja2
          python -c "
          import json
          from jinja2 import Template

          with open('bandit-report.json', 'r') as f:
              data = json.load(f)

          html_template = '''

          <!DOCTYPE html>
          <html>
          <head>
              <title>Bandit Scan Report</title>
          </head>
          <body>
              <h1>Bandit Scan Report</h1>
              <ul>
              {% for issue in data.results %}
                  <li>
                      <strong>{{ issue.test_name }}</strong>: {{ issue.issue_text }}
                      <br>Severity: {{ issue.issue_severity }}
                      <br>File: {{ issue.filename }} (Line {{ issue.line_number }})
                  </li>
              {% endfor %}
              </ul>
          </body>
          </html>
          '''
          template = Template(html_template)
          html_report = template.render(data=data)

          with open('bandit-report.html', 'w') as f:
              f.write(html_report)
          "
      - name: Upload HTML Report (Optional)
        uses: actions/upload-artifact@v4
        with:
          name: bandit-html-report
          path: bandit-report.html
