name: Deploy and DAST with OWASP ZAP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-and-scan:
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Клонирование репозитория
    - name: Checkout code
      uses: actions/checkout@v4

    # Шаг 2: Установка Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    # Шаг 3: Установка зависимостей
    - name: Install dependencies
      run: npm install

    # Шаг 4: Сборка проекта
    - name: Build the project
      run: npm run build

    # Шаг 5: Запуск приложения
    - name: Start the application
      run: npm start &
      env:
        NODE_ENV: production

    # Шаг 6: Ожидание запуска приложения
    - name: Wait for application to start
      run: sleep 10

    # Шаг 7: Загрузка Docker-образа ZAP из GHCR
    - name: Pull ZAP Docker image from GHCR
      run: docker pull ghcr.io/zaproxy/zaproxy:stable

    # Шаг 8: Запуск OWASP ZAP для DAST
    - name: Run OWASP ZAP DAST Scan
      uses: zaproxy/action-full-scan@v0.5.0
      with:
        target: 'http://localhost:8080'  # Укажите URL вашего приложения
        format: 'md'  # Экспорт результатов в Markdown
        output_file: 'zap_scan_results.md'  # Имя файла для результатов
        docker_name: 'ghcr.io/zaproxy/zaproxy:stable'  # Используемый Docker-образ из GHCR
        cmd_options: '-config api.disablekey=true'  # Отключение API-ключа

    # Шаг 9: Сохранение результатов сканирования как артефакта
    - name: Upload scan results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: zap-scan-results
        path: zap_scan_results.md

    # Шаг 10: Вывод результатов сканирования в консоль (опционально)
    - name: Display scan results
      run: cat zap_scan_results.md

    # Шаг 11: Создание Issue с результатами сканирования
    - name: Create DAST Issue with Markdown report
      if: always()
      uses: actions/github-script@v6
      with:
        script: |
          const issueTitle = "DAST Scan Results";
          const issueBody = `
            The DAST scan has been completed. Below are the results:

            Full report: [Download](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts)

            \`\`\`markdown
            $(fs.readFileSync('zap_scan_results.md').toString())
            \`\`\`
          `;
          const labels = ["dast", "security"];
          const assignees = [context.payload.sender.login];

          const issue = {
            title: issueTitle,
            body: issueBody,
            labels: labels,
            assignees: assignees
          };

          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ...issue
          });

    # Шаг 12: Очистка временных директорий
    - name: Clean up temporary directories
      if: always()
      run: |
        rm -rf ./zap-reports
