name: Deploy and DAST with OWASP ZAP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-and-scan:
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Клонирование репозитория
    - name: Checkout code
      uses: actions/checkout@v3

    # Шаг 2: Установка Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Шаг 3: Установка зависимостей
    - name: Install dependencies
      run: npm install

    # Шаг 4: Сборка проекта
    - name: Build the project
      run: npm run build

    # Шаг 5: Запуск приложения
    - name: Start the application
      run: npm start &
      env:
        NODE_ENV: production

    # Шаг 6: Ожидание запуска приложения
    - name: Wait for application to start
      run: sleep 10

    # Шаг 7: Запуск OWASP ZAP для DAST
    - name: Run OWASP ZAP DAST Scan
      uses: zaproxy/action-full-scan@v0.5.0
      with:
        target: 'http://localhost:3000'  # Укажите URL вашего приложения
        format: 'md'  # Экспорт результатов в Markdown
        output_file: 'zap_scan_results.md'  # Имя файла для результатов
        docker_name: 'owasp/zap2docker-stable'  # Используемый Docker-образ
        cmd_options: '-config api.disablekey=true'  # Отключение API-ключа

    # Шаг 8: Сохранение результатов сканирования как артефакта
    - name: Upload scan results as artifact
      uses: actions/upload-artifact@v3
      with:
        name: zap-scan-results
        path: zap_scan_results.md

    # Шаг 9: Вывод результатов сканирования в консоль (опционально)
    - name: Display scan results
      run: cat zap_scan_results.md
