name: CICD DAST

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dast-scan:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2: Установка Python и зависимостей Django
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd park  # Переходим в директорию проекта
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Шаг 3: Запуск Django-приложения в фоновом режиме
      - name: Start Django application
        run: |
          cd park  # Переходим в директорию проекта
          python manage.py migrate
          nohup python manage.py runserver 0.0.0.0:8000 > django.log 2>&1 &
          echo "Django application started on http://localhost:8000"

      # Шаг 4: Установка OWASP ZAP
      - name: Download and setup OWASP ZAP
        run: |
          wget https://github.com/zaproxy/zaproxy/releases/download/v2.12.0/ZAP_2.12.0_Linux.tar.gz -O zap.tar.gz
          tar -xzf zap.tar.gz
          mv ZAP_* zap
          chmod +x zap/bin/zap-baseline.py

      # Шаг 5: Запуск сканирования OWASP ZAP
      - name: Run OWASP ZAP Baseline Scan
        run: |
          ./zap/bin/zap-baseline.py \
            -t http://localhost:8000 \
            -r zap_report.html \
            -g zap_config.zap \
            -l WARN \
            -x zap.xml

      # Шаг 6: Преобразование HTML-отчета в Markdown
      - name: Convert HTML report to Markdown
        run: |
          pandoc -f html -t markdown zap_report.html -o zap_report.md
          cat zap_report.md

      # Шаг 7: Публикация отчета
      - name: Upload ZAP Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.md
