name: DAST

on:
  push:
    branches:
      - main

jobs:
  dast-scan:
    runs-on: ubuntu-latest
    steps:
      # Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # Установка Python и зависимостей
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Подготовка отчёта
      - name: Prepare report file
        run: |
          touch report_md.md
          chmod 666 report_md.md

      # Запуск Django-сервера
      - name: Start Django application with uWSGI
        run: |
          pip install uwsgi
          nohup uwsgi --http 0.0.0.0:8000 --module parking.wsgi --workers 2 --threads 1 > django.log 2>&1 &
          echo "Waiting for Django application to start..."
          until curl -s http://localhost:8000/myparking/ > /dev/null; do
            echo "Still waiting..."
            sleep 10
          done
          echo "Django is running."

      # Запуск OWASP ZAP
      - name: Run OWASP ZAP Full Scan
        run: |
          docker run --network host --rm -v $(pwd):/zap/wrk/:rw,z -t --user root ghcr.io/zaproxy/zaproxy:latest \
            zap-full-scan.py \
            -t http://localhost:8000/myparking/ \
            -r zap_report.html \
            -J zap_report.json \
            -w report_md.md \
            -z "-config scanner.threadPerHost=1" \
            -I \  # Корректный флаг для игнорирования предупреждений
            -I || echo "ZAP scan completed with warnings."

      # Генерация отчёта
      - name: Generate Markdown Report
        run: |
          if [ ! -f zap_report.json ]; then
            echo "# ZAP Scan Report" > report_md.md
            echo "No JSON report was generated by ZAP." >> report_md.md
          else
            echo "# ZAP Scan Results" > report_md.md
            jq -r '.alerts[] | "### \(.alert)\n- Risk: \(.riskdesc)\n- URL: \(.url)\n- Description: \(.desc)\n- Solution: \(.solution)\n"' zap_report.json >> report_md.md || true
            jq -r '.warnings[] | "### \(.alert)\n- Risk: \(.riskdesc)\n- URL: \(.url)\n- Description: \(.desc)\n- Solution: \(.solution)\n"' zap_report.json >> report_md.md || true
          fi
          cat report_md.md

      # Публикация отчёта
      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: |
            report_md.md
            zap_report.html
            zap_report.json

      # Очистка
      - name: Cleanup processes
        run: |
          pkill -f uwsgi || true
