name: DAST Scan with OWASP ZAP

on:
  schedule:
    - cron: '0 0 * * *'  # Ежедневный запуск в полночь
  workflow_dispatch:      # Ручной запуск через интерфейс GitHub

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run OWASP ZAP Docker Scan
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          target: 'http://89.169.164.174:80'
          cmd_options: '-a'
          format: 'html json sarif'         # Форматы отчетов

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-html-report
          path: zap-report.html

      - name: Upload JSON Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-json-report
          path: zap-report.json

      - name: Upload SARIF Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-sarif-report
          path: zap-report.sarif

      - name: Import SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: zap-report.sarif
