name: DAST Scan

on:
  push:
    branches:
      - main

jobs:
  dast:
    runs-on: self-hosted
    container:
      image: owasp/zap2docker-stable
      options: --user root --network host

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Check current user
        run: whoami

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run DAST Scan
        run: |
          echo "Starting DAST scan..."
          zap-baseline.py -t http://89.169.164.174:80 -a -r zap-report.html -w zap-report.md || echo "DAST scan failed"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: |
            zap-report.html
            zap-report.md
