name: DAST Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dast:
    runs-on: self-hosted  # Используем self-hosted runner
    container:
      image: owasp/zap2docker-live  # Используем образ OWASP ZAP
      options: --user root  # Опционально, для прав root в контейнере

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run DAST Scan
        run: |
          echo "Starting DAST scan..."
          zap-baseline.py -t http://your-target-url.com -a -r zap-report.html -w zap-report.md || echo "DAST scan failed"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: zap-reports
          path: |
            zap-report.html
            zap-report.md
