name: DAST Scan

on:
  push:
    branches:
      - main

jobs:
  dast:
    runs-on: self-hosted  # Используем self-hosted runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Download OWASP ZAP
        run: |
          echo "Downloading OWASP ZAP..."
          ZAP_VERSION="2.16.0"  # Укажите нужную версию ZAP
          ZAP_URL="https://github.com/zaproxy/zaproxy/releases/download/v${ZAP_VERSION}/ZAP_${ZAP_VERSION}_Linux.tar.gz"
          wget -O zap.tar.gz $ZAP_URL
          tar -xzf zap.tar.gz
          rm zap.tar.gz
          echo "OWASP ZAP downloaded and extracted."

      - name: Run DAST Scan
        run: |
          echo "Starting DAST scan..."
          ./ZAP_2.16.0/zap.sh -cmd -autorun /ZAP/zap-script.js -dir ./zap-reports -r zap-report.html -w zap-report.md || echo "DAST scan failed"
          echo "DAST scan completed."
          echo "Checking if reports were created..."
          ls -R zap-reports

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: ./zap-reports
            zap-reports/zap-report.html
            zap-reports/zap-report.md
