name: DAST Scan

on:
  push:
    branches:
      - main

jobs:
  dast-scan:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download ZAP
        run: |
          mkdir -p ZAP_2.16.0
          wget -qO- https://github.com/zaproxy/zaproxy/releases/download/v2.16.0/ZAP_2.16.0_Linux.tar.gz | tar xz -C ZAP_2.16.0 --strip-components=1

      - name: Create reports directory
        run: |
          mkdir -p /home/pterrosamoilov/actions-runner/_work/park/park/zap-reports
          chmod 777 /home/pterrosamoilov/actions-runner/_work/park/park/zap-reports

      - name: Run DAST scan
        run: |
          ./ZAP_2.16.0/zap.sh -cmd -autorun /ZAP/zap-script.js -dir /home/pterrosamoilov/actions-runner/_work/park/park/zap-reports -r zap-report.html -w zap-report.md || echo "DAST scan failed"

      - name: Upload ZAP reports
        uses: actions/upload-artifact@v3
        with:
          name: zap-reports
          path: /home/pterrosamoilov/actions-runner/_work/park/park/zap-reports
