name: DAST Scan
on:
  push:
    branches:
      - main
jobs:
  dast-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: temurin

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Download ZAP
        run: |
          mkdir -p ZAP_2.16.0
          wget -qO- https://github.com/zaproxy/zaproxy/releases/download/v2.16.0/ZAP_2.16.0_Linux.tar.gz | tar xz -C ZAP_2.16.0 --strip-components=1

          # Проверка, что ZAP скачан
          if [ ! -f "./ZAP_2.16.0/zap.sh" ]; then
            echo "Error: ZAP download failed."
            exit 1
          fi

      - name: Create reports directory
        run: |
          mkdir -p /home/actions-runner/_work/park/park/zap-reports
          chmod 777 /home/actions-runner/_work/park/park/zap-reports

          # Проверка, что директория создана
          if [ ! -d "/home/actions-runner/_work/park/park/zap-reports" ]; then
            echo "Error: Failed to create reports directory."
            exit 1
          fi

      - name: Stop ZAP if running
        run: |
          # Останавливаем ZAP, если он уже запущен
          pkill -f "zap.sh" || echo "ZAP is not running."

      - name: Start ZAP in background
        run: |
          # Используем порт 8090, если 8080 занят
          if lsof -i :8080; then
            echo "Port 8080 is in use. Using port 8090 instead."
            ZAP_PORT=8090
          else
            ZAP_PORT=8080
          fi

          ./ZAP_2.16.
