name: SAST

on:
  push:
    branches:
      - main

jobs:
  build-and-sast:
    runs-on: ubuntu-latest
    steps:
      # Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # Установка Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Установка Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Устанавливаем ESLint, Stylelint, HTMLHint и необходимые плагины
          npm install -g eslint@latest stylelint@latest htmlhint eslint-html-reporter bandit-html

      # Настройка конфигов для SAST
      - name: Configure SAST tools
        run: |
          # Создаём конфиг для ESLint (v9+)
          echo 'export default [
            {
              rules: {
                "no-console": "warn",
                "no-debugger": "error"
              }
            }
          ];' > eslint.config.js

          # Создаём конфиг для Stylelint
          echo '{
            "extends": "stylelint-config-standard"
          }' > .stylelintrc.json

          # Создаём конфиг для HTMLHint
          echo '{
            "tagname-lowercase": true,
            "attr-lowercase": true
          }' > .htmlhintrc

      # Запуск Django-сервера
      - name: Start Django application
        run: |
          python manage.py check --deploy
          python manage.py makemigrations --dry-run --check
          python manage.py runserver 0.0.0.0:8000 &
          sleep 10

      # SAST для Python (Bandit)
      - name: Run Bandit (Python)
        run: |
          bandit -r . -f json -o bandit-report.json || true
          bandit-html -i bandit-report.json -o bandit-report.html || true  # Генерация HTML

      # SAST для JavaScript (ESLint)
      - name: Run ESLint (JavaScript)
        run: |
          eslint . --ext .js,.jsx --format json -o eslint-report.json || true
          eslint-html-reporter -i eslint-report.json -o eslint-report.html || true  # Генерация HTML

      # SAST для CSS (Stylelint)
      - name: Run Stylelint (CSS)
        run: |
          stylelint "**/*.{css,scss}" --formatter json > stylelint-report.json || true
          stylelint "**/*.{css,scss}" --formatter html > stylelint-report.html || true  # Генерация HTML

      # SAST для HTML (HTMLHint)
      - name: Run HTMLHint (HTML)
        run: |
          htmlhint "**/*.html" --format json > htmlhint-report.json || true  # Исправлен формат

      # Генерация объединённого Markdown-отчёта
      - name: Generate Combined SAST Report
        run: |
          echo "# SAST Scan Results" > sast-report.md
          
          # Python (Bandit)
          echo "## Python (Bandit)" >> sast-report.md
          if [ -f bandit-report.json ]; then
            jq -r '.results[] | "### \(.test_id)\n- Severity: \(.issue_severity)\n- Line: \(.line_number)\n- File: \(.filename)\n- Issue: \(.issue_text)\n"' bandit-report.json >> sast-report.md || true
          else
            echo "No Python issues found." >> sast-report.md
          fi

          # JavaScript (ESLint)
          echo "## JavaScript (ESLint)" >> sast-report.md
          if [ -f eslint-report.json ]; then
            jq -r '.[] | "### \(.ruleId)\n- Severity: \(.severity)\n- Line: \(.line)\n- File: \(.filePath)\n- Message: \(.message)\n"' eslint-report.json >> sast-report.md || true
          else
            echo "No JavaScript issues found." >> sast-report.md
          fi

          # CSS (Stylelint)
          echo "## CSS (Stylelint)" >> sast-report.md
          if [ -f stylelint-report.json ]; then
            jq -r '.[] | "### \(.rule)\n- Severity: \(.severity)\n- Line: \(.line)\n- File: \(.source)\n- Message: \(.text)\n"' stylelint-report.json >> sast-report.md || true
          else
            echo "No CSS issues found." >> sast-report.md
          fi

          # HTML (HTMLHint)
          echo "## HTML (HTMLHint)" >> sast-report.md
          if [ -f htmlhint-report.json ]; then
            jq -r '.[] | "### \(.rule.id)\n- Severity: \(.rule.severity)\n- Line: \(.line)\n- File: \(.file)\n- Message: \(.message)\n"' htmlhint-report.json >> sast-report.md || true
          else
            echo "No HTML issues found." >> sast-report.md
          fi

      # Публикация отчётов
      - name: Upload SAST Reports
        uses: actions/upload-artifact@v4
        with:
          name: sast-reports
          path: |
            bandit-report.json
            eslint-report.json
            stylelint-report.json
            htmlhint-report.json
            bandit-report.html
            eslint-report.html
            stylelint-report.html
            sast-report.md

      # Создание GitHub Issue
      - name: Create SAST Issue
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const issueTitle = "Security Scan Results";
            const issueBody = `
              ## SAST Report
              Full reports: [Download](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts)

              ### Python (Bandit)
              \`\`\`markdown
              ${fs.readFileSync('sast-report.md').toString().split('## JavaScript')[0] || 'No issues found'}
              \`\`\`

              ### JavaScript (ESLint)
              \`\`\`markdown
              ${fs.readFileSync('sast-report.md').toString().match(/## JavaScript.*?(?=## CSS)/s)[0] || 'No issues found'}
              \`\`\`

              ### CSS (Stylelint)
              \`\`\`markdown
              ${fs.readFileSync('sast-report.md').toString().match(/## CSS.*?(?=## HTML)/s)[0] || 'No issues found'}
              \`\`\`

              ### HTML (HTMLHint)
              \`\`\`markdown
              ${fs.readFileSync('sast-report.md').toString().match(/## HTML.*$/s)[0] || 'No issues found'}
              \`\`\`
            `;
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
              labels: ["security", "sast"],
              assignees: [context.actor]
            });
