jobs:
  sast:
    name: SAST (CodeQL)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript  # Убедитесь, что язык указан верно
          # Если проект на Python/PHP/Java, замените "javascript"

      - name: Analyze with CodeQL
        uses: github/codeql-action/analyze@v2
        continue-on-error: true

      - name: Verify SARIF file exists
        run: |
          if [ ! -f results.sarif ]; then
            echo "Ошибка: results.sarif не найден!"
            exit 1
          fi

      - name: Upload SARIF Report
        uses: actions/upload-artifact@v4
        with:
          name: codeql-results
          path: results.sarif

  dast:
    name: DAST (OWASP ZAP)
    runs-on: ubuntu-latest
    needs: [sast]  # Зависит от завершения SAST
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Check server availability
        run: |
          curl -I http://89.169.164.174 || exit 1

      - name: Download SAST Artifacts
        uses: actions/download-artifact@v4
        with:
          name: codeql-results  # Точно совпадает с именем из SAST-джоба
          path: ./sast-reports  # Укажите путь для сохранения

      - name: Verify artifact download
        run: |
          echo "Проверка существования SARIF-файла:"
          ls -la ./sast-reports

      - name: Run ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          target: 'http://89.169.164.174'
          format: html
          report_file: zap_dast_report.html
          cmd_options: '-I -T 60'

      - name: Generate Markdown Report
        run: |
          echo "### Результаты сканирования OWASP ZAP" > zap_summary.md
          echo "**Высокий риск:** $(grep -oP '(?<=High</td><td>)[0-9]+' zap_dast_report.html)" >> zap_summary.md
          echo "**Средний риск:** $(grep -oP '(?<=Medium</td><td>)[0-9]+' zap_dast_report.html)" >> zap_summary.md
          echo "**Низкий риск:** $(grep -oP '(?<=Low</td><td>)[0-9]+' zap_dast_report.html)" >> zap_summary.md

      - name: Upload DAST Reports
        uses: actions/upload-artifact@v4
        with:
          name: dast-reports
          path: |
            zap_dast_report.html
            zap_summary.md
