name: Security Pipeline for Park Project
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * 1'

jobs:
  sast:
    name: SAST (CodeQL)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        continue-on-error: true

      - name: Upload SAST Report
        uses: actions/upload-artifact@v4
        with:
          name: codeql-results
          path: results.sarif

  dast:
    name: DAST (OWASP ZAP)
    runs-on: ubuntu-latest
    needs: sast
    permissions:
      contents: read
      actions: read
      checks: write
    steps:
      - name: Check server availability
        run: curl -I http://89.169.164.174 || exit 1

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.10.0  # Используйте последнюю версию
        with:
          target: 'http://89.169.164.174'
          format: html
          report_file: zap_dast_report.html
          cmd_options: '-I -T 60'
          token: ${{ secrets.GITHUB_TOKEN }}  # Явно передайте токен

      - name: Generate Markdown Report
        run: |
          echo "### ZAP Scan Results" > zap_dast_summary.md
          echo "**High:** $(grep -oP '(?<=High</td><td>)[0-9]+' zap_dast_report.html)" >> zap_dast_summary.md
          echo "**Medium:** $(grep -oP '(?<=Medium</td><td>)[0-9]+' zap_dast_report.html)" >> zap_dast_summary.md
          echo "**Low:** $(grep -oP '(?<=Low</td><td>)[0-9]+' zap_dast_report.html)" >> zap_dast_summary.md

      - name: Upload DAST Reports
        uses: actions/upload-artifact@v4
        with:
          name: dast-reports
          path: |
            zap_dast_report.html
            zap_dast_summary.md
