name: Semgrep SAST Scan

on:
  push:
    branches:
      - main  # Запускать при пуше в ветку main
  pull_request:
    branches:
      - main  # Запускать при создании пул-реквеста в ветку main
  schedule:
    - cron: '0 0 * * *'  # Ежедневный запуск в полночь
  workflow_dispatch:  # Ручной запуск через интерфейс GitHub

jobs:
  semgrep-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upgrade Semgrep
        run: pip install --upgrade semgrep

      - name: Run Semgrep SAST
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/python
          output_format: sarif
          output_file: semgrep-report.sarif

      - name: Check if SARIF file exists
        id: check_sarif
        run: |
          if [ -f "semgrep-report.sarif" ]; then
            echo "sarif_file_exists=true" >> $GITHUB_OUTPUT
          else
            echo "sarif_file_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Import SARIF to GitHub Code Scanning
        if: steps.check_sarif.outputs.sarif_file_exists == 'true'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-report.sarif
