name: Semgrep SAST Scan

on:
  push:
    branches:
      - main  # Запускать при пуше в ветку main
  pull_request:
    branches:
      - main  # Запускать при создании пул-реквеста в ветку main
  schedule:
    - cron: '0 0 * * *'  # Ежедневный запуск в полночь
  workflow_dispatch:  # Ручной запуск через интерфейс GitHub

jobs:
  semgrep-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Используем актуальную версию actions/checkout

      - name: Run Semgrep SAST
        uses: returntocorp/semgrep-action@v1  # Официальный action для Semgrep
        with:
          config: p/python --verbose # Используем стандартный конфиг для Python
          output_format: sarif  # Формат отчета (SARIF для интеграции с GitHub Code Scanning)
          output_file: semgrep-report.sarif  # Имя файла отчета

      - name: Upload SARIF Report
        uses: actions/upload-artifact@v4  # Загружаем отчет как артефакт
        with:
          name: semgrep-sarif-report
          path: semgrep-report.sarif

      - name: Import SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2  # Импортируем отчет в GitHub Code Scanning
        with:
          sarif_file: semgrep-report.sarif
