name: SSSD

on:
  push:
    branches:
      - main

jobs:
  dast-scan:
    runs-on: ubuntu-latest
    steps:
      # Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # Установка Python и зависимостей
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Запуск Django-сервера (слушает все интерфейсы)
      - name: Start Django application with uWSGI
        run: |
          pip install uwsgi
          nohup uwsgi --http 0.0.0.0:8000 --module parking.wsgi > django.log 2>&1 &
          echo "Waiting for Django application to start..."
          sleep 30  # Увеличен таймаут для стабильного запуска
          echo "Django application started on http://0.0.0.0:8000"

      # Проверка доступности Django
      - name: Check Django server availability
        run: |
          timeout=120
          while [ $timeout -gt 0 ]; do
            curl -sL http://localhost:8000/myparking/ | grep -q '<!DOCTYPE html>' && break
            echo "Waiting for Django server... ($timeout seconds left)"
            sleep 5
            timeout=$((timeout - 5))
          done
          if [ $timeout -le 0 ]; then
            echo "Django server failed to start. Continuing anyway..."
          fi

      # Запуск OWASP ZAP Baseline Scan
      - name: Run OWASP ZAP Scan (ignoring errors)
        run: |
          docker run --network host --rm -v $(pwd):/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:latest \
            zap-baseline.py \
            -t http://localhost:8000/myparking/ \
            -r zap_report.json \
            -g zap_config.zap \
            -l INFO \  # Включаем все сообщения (INFO, WARN, FAIL)
            -i zap-baseline.ignore \
            -x zap.xml \
            || true  # Продолжаем пайплайн даже при ошибке

      # Проверка и преобразование отчёта
      - name: Generate Markdown Report
        run: |
          # Если отчёт не создан — формируем пустой
          if [ ! -f zap_report.json ]; then
            echo "# ZAP Scan Report" > zap_report.md
            echo "No report generated. Check logs for details." >> zap_report.md
          else
            # Проверяем валидность JSON и преобразуем
            echo "# ZAP Scan Results" > zap_report.md
            echo "" >> zap_report.md

            # Обработка всех категорий
            echo "## Critical/High/Medium Alerts" >> zap_report.md
            jq -e '.alerts | length > 0' zap_report.json >/dev/null && \
              jq -r '.alerts[] | "### \(.alert)\n\n- Risk: \(.riskdesc)\n- Confidence: \(.confidence)\n- URL: \(.url)\n- Description: \(.otherinfo)\n- Solution: \(.solution)\n\n"' \
              zap_report.json >> zap_report.md || echo "No critical alerts found."

            echo "## Warnings" >> zap_report.md
            jq -e '.warnings | length > 0' zap_report.json >/dev/null && \
              jq -r '.warnings[] | "### \(.alert)\n\n- Risk: \(.riskdesc)\n- Confidence: \(.confidence)\n- URL: \(.url)\n- Description: \(.otherinfo)\n- Solution: \(.solution)\n\n"' \
              zap_report.json >> zap_report.md || echo "No warnings found."

            echo "## Informational Messages" >> zap_report.md
            jq -e '.informational | length > 0' zap_report.json >/dev/null && \
              jq -r '.informational[] | "### \(.alert)\n\n- Risk: \(.riskdesc)\n- Confidence: \(.confidence)\n- URL: \(.url)\n- Description: \(.otherinfo)\n- Solution: \(.solution)\n\n"' \
              zap_report.json >> zap_report.md || echo "No informational messages found."
          fi

          # Выводим отчёт в логи (даже если он пуст)
          cat zap_report.md

      # Публикация отчёта
      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.md

      # Показать логи Django
      - name: Show Django logs
        run: cat django.log

      # Показать логи ZAP
      - name: Show ZAP logs
        run: cat zap_report.json || echo "No ZAP report found."

      # Очистка процессов
      - name: Cleanup
        run: |
          pkill -f uwsgi || true
