name: SSSD

on:
  push:
    branches:
      - main

jobs:
  dast-scan:
    runs-on: ubuntu-latest
    steps:
      # Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # Установка Python и зависимостей
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Запуск Django-сервера с uWSGI
      - name: Start Django application with uWSGI
        run: |
          pip install uwsgi
          nohup uwsgi --http :8000 --module parking.wsgi > django.log 2>&1 &
          echo "Waiting for Django application to start..."
          sleep 20
          echo "Django application started on http://127.0.0.1:8000"

      # Настройка NGINX для порта 8080
      - name: Configure NGINX for port 8080
        run: |
          sudo apt-get update
          sudo apt-get install -y nginx
          sudo systemctl stop nginx
          echo "server {
            listen 8080;
            server_name localhost;
            location / {
              proxy_pass http://127.0.0.1:8000;
              proxy_set_header Host \$host;
              proxy_set_header X-Real-IP \$remote_addr;
              proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
            }
          }" | sudo tee /etc/nginx/sites-available/django
          sudo ln -s /etc/nginx/sites-available/django /etc/nginx/sites-enabled/
          sudo nginx -t || true
          sudo systemctl start nginx
          echo "NGINX configured to listen on port 8080 and proxy to 8000"

      # Проверка доступности Django через NGINX
      - name: Check if Django server is running via NGINX
        run: |
          timeout=120
          while [ $timeout -gt 0 ]; do
            curl -sL http://localhost:8080/myparking/ | grep -q ' ' && break
            echo "Waiting for Django server via NGINX... ($timeout seconds left)"
            sleep 5
            timeout=$((timeout - 5))
          done
          if [ $timeout -le 0 ]; then
            echo "Django server failed to start within the timeout period."
            exit 1
          fi
          echo "Django server is running via NGINX."

      # Показать логи Django (в случае ошибки)
      - name: Show Django logs
        if: failure()
        run: |
          cat django.log

      # Создание файла исключений
      - name: Create zap-baseline.ignore file
        run: |
          echo "10010  # Cookie No HttpOnly Flag" > zap-baseline.ignore
          echo "10017  # Cross-Domain JavaScript Source File Inclusion" >> zap-baseline.ignore
          echo "10038  # Content Security Policy (CSP) Header Not Set" >> zap-baseline.ignore
          echo "10063  # Permissions Policy Header Not Set" >> zap-baseline.ignore
          echo "90003  # Sub Resource Integrity Attribute Missing" >> zap-baseline.ignore
          echo "90004  # Insufficient Site Isolation Against Spectre Vulnerability" >> zap-baseline.ignore

      # Запуск OWASP ZAP Baseline Scan
      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run --network host --rm -v $(pwd):/zap/wrk/:rw -u root -t ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
            -t http://localhost:8080/myparking/ \
            -r zap_report.json \
            -g zap_config.zap \
            -l PASS \
            -i zap-baseline.ignore \
            -x zap.xml || true

      # Проверка наличия и содержимого zap_report.json
      - name: Show zap_report.json content
        if: always()
        run: |
          if [ -f zap_report.json ]; then
            cat zap_report.json
          else
            echo "File zap_report.json does not exist."
          fi

      # Установка jq
      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      # Преобразование JSON-отчета ZAP в Markdown
      - name: Convert JSON report to Markdown
        run: |
          if [ ! -f zap_report.json ]; then
            echo "File zap_report.json not found. Exiting without generating Markdown report."
            exit 0
          fi
          if ! jq empty zap_report.json; then
            echo "Invalid JSON in zap_report.json. Exiting without generating Markdown report."
            exit 0
          fi
          echo "# ZAP Scan Results" > zap_report.md
          jq -r '.alerts[] | "## Alert: \(.alert)\n\n- Risk: \(.riskdesc)\n- Confidence: \(.confidence)\n- URL: \(.url)\n- Description: \(.otherinfo)\n- Solution: \(.solution)\n\n"' zap_report.json >> zap_report.md
          cat zap_report.md

      # Публикация отчета
      - name: Upload ZAP Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.md
