name: SSSD

on:
  push:
    branches:
      - main

jobs:
  build-and-sast:
  dast-scan:
    runs-on: ubuntu-latest
    needs: build-and-sast
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

#      - name: Start local Django server
#        run: |
#          python manage.py runserver 0.0.0.0:8000 &
#          sleep 10

      - name: Start Django application with uWSGI
        run: |
          pip install uwsgi
          nohup uwsgi --http :8000 --module parking.wsgi > django.log 2>&1 &
          echo "Waiting for Django application to start..."
          sleep 10
          echo "Django application started on http://localhost:8000"

      # Запуск сканирования OWASP ZAP через Docker
      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run --rm -v $(pwd):/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
            -t http://localhost:8000 \
            -r zap_report.html \
            -g zap_config.zap \
            -l WARN \
            -x zap.xml
      # Преобразование HTML-отчета в Markdown
      - name: Convert HTML report to Markdown
        run: |
          pandoc -f html -t markdown zap_report.html -o zap_report.md
          cat zap_report.md
      # Публикация отчета
      - name: Upload ZAP Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.md
