name: SSSD

on:
  push:
    branches:
      - main

jobs:
  dast-scan:
    runs-on: ubuntu-latest
    steps:
      # Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # Установка Python и зависимостей
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Настройка прав доступа для рабочей директории
      - name: Set permissions for working directory
        run: |
          # Ограничиваем права только для текущего пользователя
          chmod -R u+rwx $(pwd)

      # Запуск Django-сервера (слушает все интерфейсы)
      - name: Start Django application with uWSGI
        run: |
          pip install uwsgi
          nohup uwsgi --http 0.0.0.0:8000 --module parking.wsgi > django.log 2>&1 &
          echo "Waiting for Django application to start..."
          sleep 30
          echo "Django application started on http://0.0.0.0:8000"

      # Запуск OWASP ZAP Full Scan
      - name: Run OWASP ZAP Full Scan
        run: |
          docker run --network host --rm -v $(pwd):/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:latest \
            zap-full-scan.py \
            -t http://localhost:8000/myparking/ \
            -r zap_report.html \  # HTML-отчёт
            -J zap_report.json \  # JSON-отчёт
            -w report_md.md \     # Markdown-отчёт
            -I \                  # Игнорируем все предупреждения
            || echo "ZAP scan completed with warnings or errors."

      # Генерация Markdown Report
      - name: Generate Markdown Report
        run: |
          # Проверяем, существует ли файл отчёта
          if [ ! -f report_md.md ]; then
            echo "# ZAP Scan Report" > report_md.md
            echo "No report file was generated by ZAP." >> report_md.md
          else
            echo "ZAP Markdown report successfully generated."
          fi

          # Выводим содержимое отчёта в логи
          cat report_md.md

      # Публикация отчёта
      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: |
            report_md.md
            zap_report.html
            zap_report.json

      # Очистка процессов
      - name: Cleanup processes
        run: |
          pkill -f uwsgi || true
