name: SSSD

on:
  push:
    branches:
      - main

jobs:
  dast-scan:
    runs-on: ubuntu-latest
    steps:
      # Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # Установка Python и зависимостей
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Запуск Django-сервера с uWSGI (слушает все интерфейсы)
      - name: Start Django application with uWSGI
        run: |
          pip install uwsgi
          nohup uwsgi --http 0.0.0.0:8000 --module parking.wsgi > django.log 2>&1 &
          echo "Waiting for Django application to start..."
          sleep 30
          echo "Django application started on http://0.0.0.0:8000"

      # Проверка доступности Django-сервера
      - name: Check if Django server is running
        run: |
          timeout=120
          while [ $timeout -gt 0 ]; do
            curl -sL http://localhost:8000/myparking/ | grep -q '<!DOCTYPE html>' && break
            echo "Waiting for Django server... ($timeout seconds left)"
            sleep 5
            timeout=$((timeout - 5))
          done
          if [ $timeout -le 0 ]; then
            echo "Django server failed to start within the timeout period."
            exit 1
          fi
          echo "Django server is running."

      # Показать логи Django (в случае ошибки)
      - name: Show Django logs
        if: failure()
        run: |
          cat django.log

      # Создание файла исключений
      - name: Create zap-baseline.ignore file
        run: |
          echo "10017  # Cross-Domain JavaScript Source File Inclusion" > zap-baseline.ignore
          echo "90003  # Sub Resource Integrity Attribute Missing" >> zap-baseline.ignore
          echo "90004  # Insufficient Site Isolation Against Spectre Vulnerability" >> zap-baseline.ignore
          echo "10010  # Cookie No HttpOnly Flag" >> zap-baseline.ignore
          echo "10038  # Content Security Policy (CSP) Header Not Set" >> zap-baseline.ignore
          echo "10063  # Permissions Policy Header Not Set" >> zap-baseline.ignore
          echo "10112  # Session Management Response Identified" >> zap-baseline.ignore
          echo "10111  # Authentication Request Identified" >> zap-baseline.ignore
          echo "10031  # User Controllable HTML Element Attribute (Potential XSS)" >> zap-baseline.ignore
          echo "10036  # Server Leaks Version Information via 'Server' Header" >> zap-baseline.ignore
          echo "10049  # Storable and Cacheable Content" >> zap-baseline.ignore

      # Запуск OWASP ZAP Baseline Scan
      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run --network host --rm -v $(pwd):/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:latest \
            zap-baseline.py \
            -t http://localhost:8000/myparking/ \
            -r zap_report.json \
            -g zap_config.zap \
            -l IGNORE \  # Игнорируем предупреждения и информационные сообщения
            -i zap-baseline.ignore \
            -x zap.xml || true

      # Проверка JSON-отчета
      - name: Validate and Inspect zap_report.json content
        run: |
          if [ ! -f zap_report.json ]; then
            echo "File zap_report.json not found. Exiting without generating Markdown report."
            exit 0
          fi

          echo "First 10 lines of zap_report.json:"
          head -n 10 zap_report.json || true

          # Проверка структуры JSON
          if ! jq empty zap_report.json; then
            echo "Invalid JSON content in zap_report.json. Exiting."
            exit 1
          fi

      # Преобразование JSON в Markdown
      - name: Convert JSON report to Markdown
        run: |
          echo "# ZAP Scan Results" > zap_report.md
          echo "" >> zap_report.md

          # Обработка всех типов сообщений
          echo "## Critical/High/Medium Alerts" >> zap_report.md
          if jq -e '.alerts | length' zap_report.json >/dev/null; then
            jq -r '.alerts[] | "### \(.alert)\n\n- Risk: \(.riskdesc)\n- Confidence: \(.confidence)\n- URL: \(.url)\n- Description: \(.desc)\n- Solution: \(.solution)\n\n"' zap_report.json >> zap_report.md
          else
            echo "No critical/high/medium alerts found." >> zap_report.md
          fi

          echo "## Warnings (Medium/Low)" >> zap_report.md
          if jq -e '.warnings | length' zap_report.json >/dev/null; then
            jq -r '.warnings[] | "### \(.alert)\n\n- Risk: \(.riskdesc)\n- Confidence: \(.confidence)\n- URL: \(.url)\n- Description: \(.desc)\n- Solution: \(.solution)\n\n"' zap_report.json >> zap_report.md
          else
            echo "No warnings found." >> zap_report.md
          fi

          echo "## Informational Messages" >> zap_report.md
          if jq -e '.informational | length' zap_report.json >/dev/null; then
            jq -r '.informational[] | "### \(.alert)\n\n- Risk: \(.riskdesc)\n- Confidence: \(.confidence)\n- URL: \(.url)\n- Description: \(.desc)\n- Solution: \(.solution)\n\n"' zap_report.json >> zap_report.md
          else
            echo "No informational messages found." >> zap_report.md
          fi

          cat zap_report.md

      # Публикация отчета
      - name: Upload ZAP Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.md

      # Очистка процессов
      - name: Cleanup processes
        run: |
          pkill -f uwsgi || true
