name: SSSD

on:
  push:
    branches:
      - main

jobs:
  dast-scan:
    runs-on: ubuntu-latest
    steps:
      # Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # Установка Python и зависимостей
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Создание Docker-сети
      - name: Create Docker network
        run: |
          docker network create zap-network || true

      # Запуск Django-сервера через uWSGI
      - name: Start Django application with uWSGI
        run: |
          pip install uwsgi
          nohup uwsgi --http :80 --module parking.wsgi > django.log 2>&1 &
          echo "Waiting for Django application to start..."
          sleep 20
          echo "Django application started on http://127.0.0.1:80"

      # Запуск nginx для перенаправления запросов на порт 80
      - name: Start nginx
        run: |
          sudo apt-get update
          sudo apt-get install -y nginx
          sudo rm /etc/nginx/sites-enabled/default
          echo "server {
            listen 80;
            server_name localhost;
            location / {
              proxy_pass http://127.0.0.1:80;
              proxy_set_header Host \$host;
              proxy_set_header X-Real-IP \$remote_addr;
              proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
            }
          }" | sudo tee /etc/nginx/sites-available/django
          sudo ln -s /etc/nginx/sites-available/django /etc/nginx/sites-enabled/
          sudo systemctl restart nginx
          echo "Nginx started and configured to forward requests to Django."

      # Проверка доступности Django-сервера через nginx
      - name: Check if Django server is running
        run: |
          timeout=120
          while [ $timeout -gt 0 ]; do
            curl -sL http://127.0.0.1/myparking/ | grep -q '<!DOCTYPE html>' && break
            echo "Waiting for Django server to become available... ($timeout seconds left)"
            sleep 5
            timeout=$((timeout - 5))
          done
          if [ $timeout -le 0 ]; then
            echo "Django server failed to start within the timeout period."
            exit 1
          fi
          echo "Django server is running."

      # Показать логи Django (в случае ошибки)
      - name: Show Django logs
        if: failure()
        run: |
          cat django.log

      # Показать логи nginx (в случае ошибки)
      - name: Show nginx logs
        if: failure()
        run: |
          cat /var/log/nginx/error.log

      # Запуск OWASP ZAP Baseline Scan
      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run --network zap-network --rm -v $(pwd):/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:latest \
            zap-baseline.py \
            -t http://127.0.0.1/myparking/ \
            -r zap_report.json \
            -g zap_config.zap \
            -l IGNORE \
            -i zap-baseline.ignore \
            -x zap.xml || true

      # Преобразование JSON-отчета ZAP в Markdown
      - name: Convert JSON report to Markdown
        run: |
          if [ ! -f zap_report.json ]; then
            echo "File zap_report.json not found. Exiting without generating Markdown report."
            exit 0
          fi
          echo "# ZAP Scan Results" > zap_report.md
          echo "" >> zap_report.md
          jq -r '.alerts[] | "## Alert: \(.alert)\n\n- Risk: \(.riskdesc)\n- Confidence: \(.confidence)\n- URL: \(.url)\n- Description: \(.otherinfo)\n- Solution: \(.solution)\n\n"' zap_report.json >> zap_report.md
          cat zap_report.md

      # Публикация отчета
      - name: Upload ZAP Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.md
