name: ZAP Automated Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download and run ZAP
        run: |
          ZAP_VERSION="2.16.0"  # Укажите актуальную версию
          wget https://github.com/zaproxy/zaproxy/releases/download/v2.16.0/ZAP_2.16.0_Linux.tar.gz
          tar -xzf ZAP_2.16.0_Linux.tar.gz
          ./ZAP_2.16.0/zap.sh -cmd -autorun /home/pterrosamoilov/actions-runner/_work/park/park/ZAP_2.16.0/zap-config.yaml  # Укажите правильный путь к файлу

      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report.html
